version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app-coleta-inteligente/db/custom.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=pZd/5V0axyLuvwNsdvhRyeiFNO7mzJ/DAwENLma/yPM=
      - HOSTNAME=0.0.0.0
    volumes:
      - .:/app-coleta-inteligente
      - /app-coleta-inteligente/node_module
      - next_cache:/app-coleta-inteligente/.next/cache
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: alpine:latest
    volumes:
      - ./db:/db
    command: sh -c "mkdir -p /db && touch /db/custom.db"
    restart: unless-stopped
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  next_cache:
